### PR TITLE
Add missing attribute in model.

### PR DESCRIPTION
**Pull request by uKaigo**
I made this PR to add a missing attribute to LyricResult model, and remove a f-string (it's only available in py3.6+).

### CODE REVIEW

**Comment by TAG-Epic** [comment]
Python versions older than 3.6 is not supported though?

**Comment by uKaigo** [comment]
Wait, it's not supported? I thought it was because of the code (no python 3.6 features).

Also the `python_requires` is missing in the setup.py iirc, so you can install in any version (that supports async/await)

**Review by Cafeepy — COMMENTED** [review]
Looks good to me! If possible, I would also suggest adding an attribute with the raw response dict so people who need to can just get whatever data they need, even if it isn't a class attribute, as the class attributes are a bit limiting in my opinion.

**Comment by uKaigo** [comment]
Added it.

**Review by Cafeepy — APPROVED** [review]
Thanks! With this, I think this PR should pretty much be good to go.

**Comment by AndyTempel** [comment]
Honestly drop support for lower than 3.6

**Comment by uKaigo** [comment]
Should I convert .format to f-strings too? Or leave it as is?

**Pull request merged**
