### PR TITLE
Add support for Weather.

### PR DESCRIPTION
**Pull request by volcanicer**
Right now, this PR only covers `weather-easy` which does not support lat/lon (mainly due to a lack of time oops) but I feel this is good enough to send at the moment. Reviews are most definitely welcome!

### CODE REVIEW

**Comment by AndyTempel** [comment]
Hi!
Thanks for submitting this PR. Please make sure the PR abides by PEP8 code style, build failed because of the following issues:
```
ksoftapi/models.py:47:1: E302 expected 2 blank lines, found 1
ksoftapi/models.py:64:1: E302 expected 2 blank lines, found 1
ksoftapi/apis/kumo.py:51:23: E128 continuation line under-indented for visual indent
ksoftapi/apis/kumo.py:91:23: E128 continuation line under-indented for visual indent```

**Comment by volcanicer** [comment]
Alright, I've just pushed a commit for this.

**Review by AndyTempel — APPROVED** [review]

**Comment by volcanicer** [comment]
Given the fact that most of the Kumo endpoints (including weather) will be removed from the API next month, this PR no longer has any use.

**Comment by volcanicer** [comment]
Apologies for the incorrect statement about most of the Kumo endpoints being removed. I've updated my earlier comment to reflect that only the weather endpoints are being deprecated soon.

**Pull request closed without merging**
