### PR TITLE
LyricResult missing url attribute

### PR DESCRIPTION
**Pull request by abdelrahmanyr**
The `LyricResult` object does not have `url` attribute which gives the lyrics link.

### CODE REVIEW

**Comment by GamingGeek** [comment]
Is this PR meant to add the attribute? If so, I don't think you know how pull requests work since you're trying to merge existing commits into master which are unrelated to the topic of this PR.

**Comment by uKaigo** [comment]
I already added this attribute in #10

**Comment by abdelrahmanyr** [comment]
Yes I don't know really know how pr works, should I delete it ?

**Comment by uKaigo** [comment]
You just described your PR with a thing that you didn't changed.

You should've described with something like "Sync `fix/response-code` with `master`"

I'm unsure, but I think that branch isn't supported anyway.

**Pull request closed without merging**
